version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/nbaStatsApi
      - /nbaStatsApi/node_modules
    ports:
      - "3010:3010"
      - "5858:5858"
  redis:
    image: "redis:alpine"
